### ISSUE TITLE
Functionality & Layout <Sidepanel/>

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#12]
Looking at you, SlackHQ   
**ಠ_ಠ**  
  
![300](https://cloud.githubusercontent.com/assets/3229933/8834071/85e400dc-3088-11e5-9ef3-adeab0a3ad55.jpg)

**Comment by dfosco** [comment]
SidePanel layout almost done — still needs:
 - [ ] Dropdown options

<img width="150" alt="sidepanel" src="https://cloud.githubusercontent.com/assets/3229933/8942926/74d6f1a8-354e-11e5-82c6-6fd7ebd756db.png">

**Comment by dfosco** [comment]
@brenoc Did we add this property after all? <img width="194" alt="screen shot 2015-07-28 at 2 43 08 pm" src="https://cloud.githubusercontent.com/assets/3229933/8947498/f310b7b6-3571-11e5-890c-15a3c0807205.png">

**Comment by brenoc** [comment]
@dfosco I think we should tackle this with this: https://github.com/gaearon/react-side-effect

**Comment by dfosco** [comment]
@brenoc Do we really need another package just for this? Or an ugly workaround will cost us more in terms of complexity?

**Comment by brenoc** [comment]
@dfosco I think it complies with the React way of doing things. The hack will be uglier and less maintainable than using this.

**Comment by dfosco** [comment]
@brenoc Deal! Will create a separate issue for it, though.

**Comment by brenoc** [comment]
@dfosco :+1:

**Comment by dfosco** [comment]
@brenoc I'm about to consider this closed, as the bulk of the work is done and the issue was too broad anyway — the only thing I'd like to have done before doing so is: 

 - [ ] Add the binding to toggle the dropdown on/off (remembering to rotate the icon)

Think you can kill it today? :smile:
