### ISSUE TITLE
Functionality & Layout <StatusBar/>

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#13]

**Comment by dfosco** [comment]
Faltando:

 - [ ] Alterar esquema de cores de acordo com o modo ativo

**Comment by dfosco** [comment]
@brenoc we're still missing to disable the `hide-ui` button on StatusBar when the user is in Edit Mode

**Comment by brenoc** [comment]
@dfosco ok!

**Comment by brenoc** [comment]
Fixed!
