### ISSUE TITLE
Re-render <App/> outside of <AppEditor/> when admin interface is hidden

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#18]
@brenoc @amoreira This is important to keep consistency between what users and admins are seeing and to ensure debugging won't be hard — because an error in one rendering might not appear in another.

**Comment by dfosco** [comment]
@brenoc @amoreira here are the two renderings I'm talking about: 

![re-render](https://cloud.githubusercontent.com/assets/3229933/8985318/17259040-36ad-11e5-8c3e-2353eb03f949.gif)

**Comment by brenoc** [comment]
@dfosco I was thinking about this and I faced a problem. Where would the "come-back-button" would be rendered if the AppEditor is not rendered at all?

Does it really gonna change the page rendering? The only case I case that this will make a difference is if the developer use something like this in their CSS:
```css
#storefront-container > .foo {
  something: "bar";
}
```

**Comment by dfosco** [comment]
Don't you think we should plan for the worst? I can see stuff like that happening, but to be honest I don't have enough experience to assess how big of a risk it will be

**Comment by dfosco** [comment]
@brenoc There's also the fact that we _already_ have it working this way... and due to the need to ship, I tend to prefer to leave it as is, at least for now.

**Comment by dfosco** [comment]
@brenoc I'll close this issue and leave this _as is_ for now — we'll come back to it if we encounter any problems when testing.
