### ISSUE TITLE
Add property to <body> tag to stop viewport scrolling when <SidePanel/> is open

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#20]
@brenoc recommended we use [react-side-effect](https://github.com/gaearon/react-side-effect) to tackle it, as the body is too much above the scope of the components are working on — anything hand-coded could be way too brittle and _hackish_.

```css
body {
  overflow-y: hidden;
}
```

**Comment by dfosco** [comment]
So... this is working. I added the `overflow-y: hidden` to the actual SidePanel a while back and it solved the issue.

**Comment by brenoc** [comment]
What
