### ISSUE TITLE
Kill ComponentEditMode and ComponentPlaceholder

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#25]
Or rather, shift this responsibility from the app's component to the storefront itself. Let's see if we can work this out this week.

\+ @brenoc @bellacorbo @tamorim

**Comment by dfosco** [comment]
@brenoc @bellacorbo @tamorim We should tackle this “structural UX” for the Editor sometime soon — we are focused on the components now, but let's not let these slide! :smiley:

**Comment by brenoc** [comment]
@dfosco Oh! This is already done!

**Comment by dfosco** [comment]
:ok_hand:
