### ISSUE TITLE
WorkspaceStatusbar

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#32]
I'll add it to the layout on the SidePanel and @brenoc will pull in the data

**Comment by dfosco** [comment]
@brenoc Just added the statusbar inside the SidePanel at `editors/AppEditor/MobileContainer/MobileSidePanel/index.js`.

Don't you think that's subtle enough?

<img width="318" alt="screen shot 2015-10-26 at 3 56 03 pm" src="https://cloud.githubusercontent.com/assets/3229933/10737654/95ec9c88-7bfa-11e5-8315-1614715a3ba5.png">

**Comment by dfosco** [comment]
@brenoc Do you think this is worth implementing or we'll just inform on `console.log()`? 

I'd rather have it indicated more clearly in the interface as shown in the screenshot above, but we have to close this issue regardless :grin:

**Comment by brenoc** [comment]
@dfosco that's good for now :+1:

**Comment by dfosco** [comment]
Latest iteration shown below. 

@amoreira will pull the data into the layout prototyped and we'll merge into master.

<img width="319" alt="screen shot 2015-10-28 at 10 28 57 pm" src="https://cloud.githubusercontent.com/assets/3229933/10807126/67668cdc-7dc3-11e5-9729-a3749319fad9.png">

**Comment by brenoc** [comment]
@dfosco What's the purpose of the green dots again?

**Comment by dfosco** [comment]
@brenoc an affordance for showing the user the apps are installed — the green dots never really change color, but makes it easier for the user to understand there are the apps loaded.

**Comment by brenoc** [comment]
@dfosco I see, I would add a `title` attribute to the dots DOM though, something like:

> App instalado

**Comment by dfosco** [comment]
@brenoc Perfect!

**Comment by dfosco** [comment]
Closing this one, as the purpose of the issue is already done! 

Pending bugs running on #33 and #35.
