### ISSUE TITLE
Should Topbar remain on MobileSidePanel

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#34]
I'm not sure this makes a lot of sense for the first release of the editor for developers.

Seeing that the workspace indicator will already have functionality, leaving this mocked user photo and links would be weird. I'd say we remove them until we have the logout/vtex admin functionality in place.

![screen shot 2015-10-29 at 02 16 02](https://cloud.githubusercontent.com/assets/3229933/10809956/0d82b680-7de3-11e5-95d9-c32346d284d4.png)

What do you think?

**Comment by brenoc** [comment]
I agree with you. 

What do you think @bellacorbo

**Comment by dfosco** [comment]
@brenoc @bellacorbo I separated the `MobileTopBar` into a component of it's own and uninstantiated it — but it's readily available if we want to add it further down the road.
