### ISSUE TITLE
Escopar CSS para não afetar storefront-theme/storefront-apps

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#5]
Mim ajuda @brenoc. 

CSS-Modules não resolve mesmo? Se não resolver eu me viro, mas seria legal usar o código do Styleguide sem precisar mexer em nada nele — afinal, a ideia é essa :disappointed: 

O problema **grave** é que se o CSS não for todo escopado as classes dos apps instalados podem afetar os temas e vice-versa. :scream: :scream: :scream:

Tá certo ou to viajando?

**Comment by brenoc** [comment]
Ta certo, grande dilema da sociedade atual:

https://speakerdeck.com/vjeux/react-css-in-js

**Comment by brenoc** [comment]
Quer dizer, desde sempre

**Comment by dfosco** [comment]
aaaaaargh

**Comment by brenoc** [comment]
kkkk
