### ISSUE TITLE
Support activating buttons via keyboard keypress

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/storefront-editor#8]
Some references to help us solve this issue:

 - https://facebook.github.io/react/docs/events.html#keyboard-events
 - http://stackoverflow.com/questions/28102746/how-to-trigger-keypress-event-in-react-js
 - http://webaim.org/techniques/javascript/eventhandlers#onclick

**Comment by dfosco** [comment]
@brenoc me manda o repositório que você encontrou que consertava esse problema no React?

**Comment by dfosco** [comment]
Alterar JS handler no botão para permitir ativação pelo teclado

**Comment by brenoc** [comment]
@dfosco Do you mean keyboard shortcuts? If so, I'm leaving that for future reference: https://www.npmjs.com/package/react-hotkey

**Comment by dfosco** [comment]
@brenoc Not really, just meant being able to navigate the page using tab and click the selected item through the keyboard.

That's mainly an accessibility concern, but it might be too specific for us to worry about it right now.

**Comment by dfosco** [comment]
Closing this issue, as we're not even doing the desktop version for now.
